version: "3"
services:
        mongo:
            container_name: mongo
            command: mongod --quiet --logpath /dev/null
            restart: always
            image: mongo
            volumes:
              - ./data:/data/db
            ports:
              - '27017:27017'

        hukuki-backend:
            container_name: hukuki
            build:
              context: .
            # command: nodemon server.js localhost 8080
            restart: always
            ports:
              - 8080:8080
            links:
              - mongo
            volumes:
              - ./:/home/app
              - /home/app/node_modules
        