# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Retrieve the secret and decode it to a file
      env:
        FIREBASE_CRED: ${{ secrets.FIREBASE_CRED }}
      run: |
        mkdir cred
        echo $FIREBASE_CRED | base64 --decode > cred/cred.json
    - run: npm ci
    - name: Swagger Config
      env:
        PUBLIC_IP: "18.198.134.13"
      run: npm run swagger-autogen
    - name: Start the Server 
      env:
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        HAYSTACK_URL: "http://34.159.251.169:8000"
      run: pm2 restart NodeApp --update-env
